import QtQuick 2.0
Rectangle {

    id: models

    ListModel
    {
        id:titleTab
        ListElement
        {
            name:"NBA"
        }
        ListElement
        {
            name:"CBA"
        }
        ListElement
        {
            name:"国际足球"
        }
        ListElement
        {
            name:"西甲"
        }
        ListElement
        {
            name:"中国足球"
        }
        ListElement
        {
            name:"英超"
        }
        ListElement
        {
            name:"意甲"
        }
        ListElement
        {
            name:"德甲"
        }
        ListElement
        {
            name:"法甲"
        }
        ListElement
        {
            name:"欧冠"
        }
        ListElement
        {
            name:"欧联"
        }
        ListElement
        {
            name:"世预赛"
        }
    }

    ListModel
    {
        id:model_page_nba
        ListElement
        {
            pic1:"images/net_repair.png"
            name1:"骑士"
            score1:"120"

            pic2:"images/net_speed.png"
            name2:"勇士"
            score2:"105"
        }
        ListElement
        {
            pic1:"images/net_repair.png"
            pic2:"images/net_speed.png"
            name1:"热火"
            name2:"尼克斯"
            score1:"120"
            score2:"105"
        }
        ListElement
        {
            pic1:"images/net_repair.png"
            pic2:"images/net_speed.png"
            name1:"公牛"
            name2:"火箭"
            score1:"120"
            score2:"105"
        }
        ListElement
        {
            pic1:"images/net_repair.png"
            name1:"骑士"
            score1:"120"

            pic2:"images/net_speed.png"
            name2:"勇士"
            score2:"105"
        }
        ListElement
        {
            pic1:"images/net_repair.png"
            pic2:"images/net_speed.png"
            name1:"热火"
            name2:"尼克斯"
            score1:"120"
            score2:"105"
        }
        ListElement
        {
            pic1:"images/net_repair.png"
            pic2:"images/net_speed.png"
            name1:"公牛"
            name2:"火箭"
            score1:"120"
            score2:"105"
        }
        ListElement
        {
            pic1:"images/net_repair.png"
            name1:"骑士"
            score1:"120"

            pic2:"images/net_speed.png"
            name2:"勇士"
            score2:"105"
        }
        ListElement
        {
            pic1:"images/net_repair.png"
            pic2:"images/net_speed.png"
            name1:"热火"
            name2:"尼克斯"
            score1:"120"
            score2:"105"
        }
        ListElement
        {
            pic1:"images/net_repair.png"
            pic2:"images/net_speed.png"
            name1:"公牛"
            name2:"火箭"
            score1:"120"
            score2:"105"
        }
    }

    ListModel
    {
        id:listTab
        ListElement
        {
            name:"比赛"
        }
        ListElement
        {
            name:"新闻"
        }
        ListElement
        {
            name:"论坛"
        }
        ListElement
        {
            name:"数据"
        }
        ListElement
        {
            name:"更多"
        }
    }
}
