import QtQuick 2.0

ListModel
{
    ListElement
    {
        pic_visit:"images/net_repair.png"
        name_visit:"骑士"
        scoreVisit:"120"
        pic_home:"images/net_speed.png"
        name_home:"勇士"
        scoreHome:"105"
        gameState:"已结束"
        gameHighlight:"比赛集锦"
    }
    ListElement
    {
        pic_visit:"images/net_repair.png"
        pic_home:"images/net_speed.png"
        name_visit:"热火"
        name_home:"尼克斯"
        scoreVisit:"120"
        scoreHome:"105"
        gameState:"已结束"
        gameHighlight:"比赛集锦"
    }
    ListElement
    {
        pic_visit:"images/net_repair.png"
        pic_home:"images/net_speed.png"
        name_visit:"公牛"
        name_home:"火箭"
        scoreVisit:"120"
        scoreHome:"105"
        gameState:"已结束"
        gameHighlight:"比赛集锦"
    }
    ListElement
    {
        pic_visit:"images/net_repair.png"
        name_visit:"骑士"
        scoreVisit:"120"

        pic_home:"images/net_speed.png"
        name_home:"勇士"
        scoreHome:"105"
        gameState:"已结束"
        gameHighlight:"比赛集锦"
    }
    ListElement
    {
        pic_visit:"images/net_repair.png"
        pic_home:"images/net_speed.png"
        name_visit:"热火"
        name_home:"尼克斯"
        scoreVisit:"120"
        scoreHome:"105"
        gameState:"已结束"
        gameHighlight:"比赛集锦"
    }
    ListElement
    {
        pic_visit:"images/net_repair.png"
        pic_home:"images/net_speed.png"
        name_visit:"公牛"
        name_home:"火箭"
        scoreVisit:"120"
        scoreHome:"105"
        gameState:"已结束"
        gameHighlight:"比赛集锦"
    }
    ListElement
    {
        pic_visit:"images/net_repair.png"
        name_visit:"骑士"
        scoreVisit:"120"
        pic_home:"images/net_speed.png"
        name_home:"勇士"
        scoreHome:"105"
        gameState:"已结束"
        gameHighlight:"比赛集锦"
    }
    ListElement
    {
        pic_visit:"images/net_repair.png"
        pic_home:"images/net_speed.png"
        name_visit:"热火"
        name_home:"尼克斯"
        scoreVisit:"120"
        scoreHome:"105"
        gameState:"已结束"
        gameHighlight:"比赛集锦"
    }
    ListElement
    {
        pic_visit:"images/net_repair.png"
        pic_home:"images/net_speed.png"
        name_visit:"公牛"
        name_home:"火箭"
        scoreVisit:"120"
        scoreHome:"105"
        gameState:"已结束"
        gameHighlight:"比赛集锦"
    }
}
